- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/main-footer.scss
- app/assets/stylesheets/main-header.scss
- app/assets/stylesheets/main-top.scss
- app/assets/stylesheets/mercari/share.scss
- app/assets/stylesheets/mixin/_clearfix.scss
- app/views/items/index.html.haml
- app/views/shared/_main-footer.html.haml
- app/views/shared/_main-header.html.haml
> トップページ ビュー実装

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/item/exhibition.scss
- app/assets/stylesheets/mixin/_sub-footer.scss
- app/views/items/new.html.haml
- app/views/shared/_sub-footer.html.haml
> 商品出品ページ ビューの実装

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/item/item-detail.scss
- app/views/items/edit.html.haml
- app/views/items/show.html.haml
> 商品詳細ページ ビュー実装

- app/assets/stylesheets/user/mypage-top.scss
- app/assets/stylesheets/user/side-bar.scss
- app/views/users/_side-bar.html.haml
- app/views/users/show.html.haml
> マイページビューの実装

- app/assets/stylesheets/mypage/users-card.scss
- app/views/users/users-card.html.haml
> カード登録画面(マイページ)ビュー実装

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/mypage/users-logout.scss
- app/views/users/logout.html.haml
> ユーザーログアウトビュー実装

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/item/item-buybuyconfirmation.scss
- app/views/items/buy_confirm.html.haml
> 商品購入確認ページビュー実装

- Gemfile
- Gemfile.lock
- README.md
- app/models/category.rb
- app/models/item.rb
- db/migrate/20190801125518_create_categories.rb
- db/migrate/20190801130616_add_ancestry_to_categories.rb
- db/schema.rb
- db/seeds.rb
Categoryにancestry導入
商品とカテゴリーの紐付けに必要なため
> Ancestry導入

- Gemfile
- Gemfile.lock
- app/models/item.rb
- app/models/prefecture.rb
active_hasnの導入
DBに依存しない静的なデータの管理のため
> Active hash導入

- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/mypage/list.scss
- app/controllers/mypage_controller.rb
- app/views/mypage/list.html.haml
- config/routes.rb
> 出品中リスト画面マークアップ

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/mypage/edit.scss
- app/controllers/mypage_controller.rb
- app/views/mypage/edit.html.haml
- config/routes.rb
> 出品商品編集画面　マークアップ

- app/assets/javascripts/category_form.js
- app/models/item.rb
- app/views/items/new.html.haml
- db/migrate/20190730030448_create_items.rb
- db/schema.rb
商品状態〜発送日数 セレクトボックス実装
サービスに必要なため
> 商品状態〜発送日数 セレクトボックス実装

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/breadcrumbs.scss
- app/views/items/index.html.haml
- app/views/mypage/_side-bar.html.haml
- app/views/mypage/card.html.haml
- app/views/mypage/edit.html.haml
- app/views/mypage/index.html.haml
- app/views/mypage/information.html.haml
- app/views/mypage/list.html.haml
- app/views/mypage/logout.html.haml
- app/views/mypage/profile.html.haml
- app/views/shared/_breadcrumbs.html.haml
- app/views/shared/_main-header.html.haml
- app/views/shared/_red-camer.html.haml
- config/breadcrumbs.rb
- config/routes.rb
#What
パンくず機能の追加
#Why
現在地をわかるようにするため
> パンくず機能の追加　サブ

- Gemfile
- Gemfile.lock
- app/models/item.rb
- app/views/items/new.html.haml
- config/application.rb
- config/locales/models/item/ja.yml
商品名、商品詳細入力機能
enum日本語化
itemモデルvalidates追加
サービスに必要なため
> 商品名,商品詳細入力機能の実装

- app/assets/javascripts/delete.js
- app/assets/stylesheets/mypage/edit.scss
- app/views/mypage/edit.html.haml
- config/routes.rb
#What
削除機能
#Why
モーダルウィンドウを表示させる
> 削除機能（モーダルウィンドウ）

- app/assets/javascripts/application.js
- app/assets/stylesheets/item/edit.scss
- app/assets/stylesheets/item/slick-2.scss
- app/controllers/items_controller.rb
- app/controllers/mypage_controller.rb
- app/models/item.rb
- app/models/user.rb
- app/views/items/edit.html.haml
- app/views/items/my_item.html.haml
- app/views/items/new.html.haml
- app/views/mypage/_item.html.haml
- app/views/mypage/list.html.haml
- config/routes.rb
- db/migrate/20190730030448_create_items.rb
- db/schema.rb
出品商品一覧ページビュー・出品商品詳細ページビュー編集
商品の情報を表示するために必要なため
> [WIP]出品商品一覧ページビュー・出品商品詳細ページビュー編集

- app/assets/javascripts/application.js
- app/assets/javascripts/slick-2.js
- app/assets/stylesheets/item/item-detail.scss
- app/controllers/items_controller.rb
- app/views/items/index.html.haml
- app/views/items/show.html.haml
> 8/11 edit 商品詳細

- app/assets/stylesheets/main-top.scss
- app/controllers/items_controller.rb
- app/views/items/index.html.haml
- app/views/shared/_item-box.html.haml
#What
トップページにitemを表示
#Why
render collectionを使用
> トップページアイテム表示

- app/assets/javascripts/image_form.js
- app/assets/stylesheets/item/item-buybuyconfirmation.scss
- app/controllers/items_controller.rb
- app/views/items/buy_confirm.html.haml
- app/views/items/show.html.haml
> 8/13 商品詳細 購入ボタン

- app/views/items/new.html.haml
出品ページからのリンクにturbo-links妨害コード記述
ユーザービリティの向上
> 出品ページからのリンクにturbo-links妨害コード記述

- app/assets/stylesheets/item/item-detail.scss
- app/controllers/items_controller.rb
- app/views/items/show.html.haml
> 8/15 商品詳細 商品画像
